# Generated by Django 4.1.6 on 2024-01-03 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ccy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Ccy',
                'verbose_name_plural': 'Ccy',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('update', models.DateField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('update', models.DateField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trader',
            },
        ),
        migrations.CreateModel(
            name='ExcelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Segment',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('trade_id', models.UUIDField(default=uuid.UUID('b1955d81-07a1-46c8-bf1a-29c732f7e59f'))),
                ('tx_date', models.DateTimeField(auto_now=True)),
                ('val_date', models.DateTimeField(auto_now=True)),
                ('buy_sell', models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], max_length=100)),
                ('amount1', models.FloatField()),
                ('amount2', models.FloatField()),
                ('deal_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fees_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('system_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('deal_pnl', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tx_comments', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='djangodbmodelsfieldsuuidfield', max_length=500, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('ccy1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency1', to='fxapp.ccy')),
                ('ccy2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency2', to='fxapp.ccy')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.product')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.dealer')),
            ],
            options={
                'verbose_name': 'Trade',
            },
        ),
        migrations.CreateModel(
            name='SystemDailyRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('rateLcy', models.FloatField(default=1.0)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.ccy')),
            ],
            options={
                'verbose_name_plural': 'SystemRates',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.segment'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
