# Generated by Django 5.1.3 on 2024-12-02 08:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ccy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='ExcelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(default='Product description')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Segment',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profile', models.CharField(default='profile', max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('update', models.DateField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trader',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('intraday_pos', models.FloatField()),
                ('ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.ccy')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('update', models.DateField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.segment')),
            ],
            options={
                'verbose_name': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='SystemDailyRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.ccy')),
            ],
            options={
                'verbose_name_plural': 'Reevaluation Rates',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('tx_date', models.DateField(auto_now=True)),
                ('val_date', models.DateTimeField()),
                ('buy_sell', models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], max_length=100)),
                ('amount1', models.FloatField()),
                ('amount2', models.FloatField()),
                ('deal_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('fees_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('system_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('ccy1_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('ccy2_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('tx_comments', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('verified', 'VERIFIED'), ('cancelled', 'CANCELLED'), ('matured', 'MATURED'), ('amend', 'AMEND')], default='verified', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('ccy1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency1', to='fxapp.ccy')),
                ('ccy2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency2', to='fxapp.ccy')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.product')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.dealer')),
            ],
            options={
                'verbose_name': 'Trade',
            },
        ),
    ]
