# Generated by Django 5.1.3 on 2024-12-07 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemdailyrates',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
