# Generated by Django 4.1.6 on 2024-01-03 11:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.UUIDField(default=uuid.UUID('8645c444-5840-4d39-bdc8-c77565a4e90f')),
        ),
    ]
