# Generated by Django 5.1.3 on 2024-12-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0002_alter_systemdailyrates_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemdailyrates',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
    ]
