# Generated by Django 4.1.6 on 2024-01-04 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0003_remove_trade_deal_pnl_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.UUIDField(default=uuid.UUID('4cf4e3ea-df08-47fc-8d44-22a01f400e13')),
        ),
    ]
