# Generated by Django 5.1.3 on 2024-12-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0003_alter_systemdailyrates_exchange_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemdailyrates',
            options={'ordering': ['-last_updated'], 'verbose_name_plural': 'Reevaluation Rates'},
        ),
    ]
