# Generated by Django 5.1.3 on 2025-03-04 02:54

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0005_countryconfig_reevaluationrates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryconfig',
            name='country',
            field=django_countries.fields.CountryField(help_text='Select your country of operations', max_length=2, unique=True, verbose_name='Country'),
        ),
    ]
