# Generated by Django 5.1.3 on 2025-03-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0006_alter_countryconfig_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatesUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField(default=False)),
                ('endpoint_used', models.CharField(max_length=50, null=True)),
            ],
            options={
                'get_latest_by': 'last_update',
            },
        ),
    ]
