# Generated by Django 4.1.6 on 2024-01-04 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0006_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.UUIDField(default=datetime.datetime(2024, 1, 4, 13, 5, 48, 374381, tzinfo=datetime.timezone.utc), editable=False, unique=True),
        ),
    ]
