# Generated by Django 4.1.6 on 2024-01-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0008_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.UUIDField(default=1704375387, editable=False, unique=True),
        ),
    ]
