# Generated by Django 4.1.6 on 2024-01-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0010_alter_trade_slug_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='253942569119419828780660577208280343044', editable=False, max_length=22, unique=True),
        ),
    ]
