# Generated by Django 4.1.6 on 2024-01-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0012_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='106298950836695856252842614960260483024', editable=False, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='val_date',
            field=models.DateTimeField(),
        ),
    ]
