# Generated by Django 4.1.6 on 2024-01-05 07:27

from django.db import migrations, models
import fxapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0013_alter_trade_trade_id_alter_trade_val_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default=fxapp.models.Trade.generate_unique_trade_id, max_length=10, unique=True),
        ),
    ]
