# Generated by Django 4.1.6 on 2024-01-05 13:12

from django.db import migrations, models
import fxapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0014_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default=fxapp.models.Trade.generate_unique_trade_id, max_length=20, unique=True),
        ),
    ]
