# Generated by Django 4.1.6 on 2024-01-05 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0015_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default=uuid.UUID('c784d02d-1f24-4386-b280-c27132057028'), max_length=100, unique=True),
        ),
    ]
