# Generated by Django 4.1.6 on 2024-01-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0019_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='519f2593-f68e-42ff-9aee-06c5d6e97422', max_length=100, unique=True),
        ),
    ]
