# Generated by Django 4.1.6 on 2024-01-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0022_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='5e0044b2-b95e-4960-8423-1d31f2e6ec9e', max_length=100, unique=True),
        ),
    ]
