# Generated by Django 4.1.6 on 2024-01-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0023_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='4418c765-d9ab-4bc5-8314-e13ef7e2e768', max_length=100, unique=True),
        ),
    ]
