# Generated by Django 4.1.6 on 2024-01-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0024_alter_trade_trade_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='slug',
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='8a268a6b-c2c9-4cfa-8479-992d44b98bfd', max_length=100, unique=True),
        ),
    ]
