# Generated by Django 4.1.6 on 2024-01-06 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0025_remove_trade_slug_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default=uuid.UUID('2d5dbfe8-5ef7-48d6-ae0f-e24c31191c19'), max_length=100, unique=True),
        ),
    ]
