# Generated by Django 4.1.6 on 2024-01-06 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0026_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
