# Generated by Django 4.1.6 on 2024-01-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0027_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='ccy1_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='ccy2_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
