# Generated by Django 4.1.6 on 2024-01-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0028_trade_ccy1_rate_trade_ccy2_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='active',
        ),
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('verified', 'VERIFIED'), ('cancelled', 'CANCELLED'), ('matured', 'MATURED'), ('amend', 'AMEND')], default='verified', max_length=100),
        ),
    ]
