# Generated by Django 4.1.6 on 2024-05-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0029_remove_trade_active_trade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='ccy1_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='ccy2_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='deal_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='fees_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='system_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.ccy')),
            ],
        ),
    ]
