# Generated by Django 4.1.6 on 2024-05-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0030_alter_trade_ccy1_rate_alter_trade_ccy2_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
