# Generated by Django 4.2.15 on 2024-10-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0033_alter_position_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
