# Generated by Django 4.2.15 on 2024-10-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0037_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Product description'),
        ),
    ]
