# Generated by Django 4.2.15 on 2024-10-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0038_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='desc',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='name',
            new_name='profile',
        ),
    ]
