# Generated by Django 5.1.3 on 2024-11-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0039_rename_desc_dealer_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='net_open_pos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
