# Generated by Django 5.1.3 on 2024-11-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0040_position_net_open_pos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='position',
            new_name='intraday_position',
        ),
        migrations.RemoveField(
            model_name='position',
            name='net_open_pos',
        ),
    ]
