# Generated by Django 5.1.3 on 2024-11-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0041_rename_position_position_intraday_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='intraday_position',
            new_name='intraday_pos',
        ),
    ]
