# Generated by Django 5.1.3 on 2024-12-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0043_alter_ccy_options_alter_systemdailyrates_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cif',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='profile',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
