# Generated by Django 5.1.3 on 2024-12-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0044_alter_customer_cif_alter_dealer_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cif',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
