# Generated by Django 5.1.3 on 2024-12-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0045_alter_customer_cif_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='profile',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
