# Generated by Django 5.1.3 on 2024-12-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0046_alter_dealer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
