# Generated by Django 5.1.3 on 2024-12-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0047_alter_segment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='profile',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
