# version: '3.8'

services:
#Angular front-end
  ficc-front:
    build: 
      context: ./web/
    ports:
      - 4200:4200
    depends_on:
      - ficc-backend
    volumes:
      - ./web/:/web
      - /web/node_modules
    command: ng serve --host 0.0.0.0 --port 4200
    environment:
      - CHOKIDAR_USEPOLLING=true 

      #django backend
  ficc-backend:
    build: 
      context: .
    restart: always
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/treasurysystem
    depends_on:
      - ficc_db
      - redis
    ports:
      - 8000:8000
    env_file:
      - ./env.dev

  ficc_db:
    image: postgres:15
    restart: always
    volumes:
      - ficc_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./env.dev

      # Redis Celery config
  redis:
    image: redis:alpine
    restart: always
  celery:
    restart: always
    build: .
    user: celeryuser
    command: celery -A treasurysystem worker -l info
    volumes:
      - .:/treasurysystem
    env_file:
      - env.dev
    depends_on:
      - redis

  celery-beat:
    build: .
    restart: always
    user: celeryuser
    command: celery -A treasurysystem beat -l info
    volumes:
      - .:/treasurysystem
    env_file:
      - env.dev
    depends_on:
      - redis

volumes:
    ficc_postgres_data:

