version: '3.8'

services:
  ficc_front:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./treasurysystem/:/treasurysystem/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  ficc_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080