version: '3.8'

services:
  ficc_front:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/treasurysystem
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    # depends_on:
    #   - ficc_db

  ficc_db:
    image: postgres:15
    restart: always
    volumes:
      - ficc_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./env.dev

volumes:
    ficc_postgres_data:
