version: '3'

x-pod-name: &pod-name
  treasurysystem-pod-v1  # Unique pod name

services:
      #django backend
  ficc-backend:
    build: 
      context: .
    restart: always
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000 --noreload"
    volumes:
      - ./:/treasurysystem:Z
    depends_on:
      - ficc_db
      - redis
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    pod: *pod-name

  ficc_db:
    image: postgres:15
    restart: always
    volumes:
      - ficc_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./env.dev
    pod: *pod-name

      # Redis Celery config
  redis:
    image: redis:alpine
    restart: always
    pod: *pod-name

  celery:
    restart: always
    build: .
    user: celeryuser
    command: celery -A treasurysystem worker -l info
    volumes:
      - .:/treasurysystem
    env_file:
      - env.dev
    pod: *pod-name

    depends_on:
      - redis

  celery-beat:
    build: .
    restart: always
    user: celeryuser
    command: celery -A treasurysystem beat -l info
    volumes:
      - .:/treasurysystem
    env_file:
      - env.dev
    pod: *pod-name

    depends_on:
      - redis

volumes:
    ficc_postgres_data:

