version: '3.8'

x-pod-name: &pod-name pod_treasurysystem

services:
  web:
    container_name: treasury_web
    build: 
      context: .
    restart: always
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000 --noreload"
    volumes:
      - ./:/treasurysystem:Z
    ports:
      - 8000:8000
    environment:
      - PGSSLMODE=require
      - PGCONNECT_TIMEOUT=30
      - PYTHONUNBUFFERED=1
    env_file:
      - ./env.dev
    dns:
      - 8.8.8.8
      - 1.1.1.1
    network_mode: "host"
    extra_hosts:
      - "host.containers.internal:192.168.127.254"
    pod: *pod-name
    depends_on:
      - redis

  redis:
    container_name: treasury_redis
    image: redis:alpine
    restart: always
    pod: *pod-name

  celery:
    container_name: treasury_celery
    build: .
    user: celeryuser
    command: celery -A treasurysystem worker -l info
    volumes:
      - ./:/treasurysystem:Z
    env_file:
      - ./env.dev
    pod: *pod-name
    depends_on:
      - redis

