# Generated by Django 5.1.3 on 2024-12-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_market', '0002_alter_approvals_approval_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='short_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
