# Generated by Django 5.1.3 on 2024-12-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_market', '0003_alter_counterparty_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='category',
            field=models.CharField(choices=[('non-group', 'Non-group'), ('group', 'Group')], max_length=25),
        ),
    ]
