# Generated by Django 5.1.3 on 2024-12-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_market', '0004_alter_counterparty_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
