# Generated by Django 5.1.3 on 2025-01-20 13:29

import django.db.models.deletion
import money_market.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapp', '0004_alter_systemdailyrates_options'),
        ('money_market', '0005_alter_counterparty_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PLX', 'Placement'), ('SPOT', 'FX SPOT'), ('FWD', 'FX FWD'), ('SWAP', 'FX SWAP'), ('GUARANTEE', 'Guarantee'), ('LC', 'Letter of Credit'), ('Discount', 'Discount of Instrument')], max_length=10, unique=True)),
                ('days_convention', models.CharField(choices=[('ACT/360', 'Actual/360'), ('ACT/365', 'Actual/365'), ('30/360', '30/360'), ('ACT/ACT', 'Actual/Actual')], max_length=10)),
                ('limit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_market.limittype')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(default=money_market.models.generate_unique_trade_id, max_length=6, unique=True)),
                ('pay_recv', models.CharField(choices=[('PAY', 'Pay'), ('RECV', 'Receive')], max_length=100)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('tx_comments', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='verified', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_market.counterparty')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapp.dealer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_market.product')),
            ],
            options={
                'verbose_name': 'Deal',
                'indexes': [models.Index(fields=['trade_id'], name='money_marke_trade_i_9c0302_idx'), models.Index(fields=['counterparty'], name='money_marke_counter_0906d0_idx')],
            },
        ),
    ]
